#!/usr/bin/env python3
"""exp38: the monodromy group of the SR5 family, measured -- transpositions from all folds.

First stage of Q7 (the complex monodromy group), built on exp37's machinery.  The plan:

1. **Full fibre at s = 1** (the real SR5): the ten real solutions from a torus-deduplicated
   census, plus the six complex ones -- the three pairs that died at the death folds
   (0.718354, 0.799244, 0.961848), obtained by seeding each fold's kernel direction just before
   it and tracking through the fold with the complex Newton corrector.  Expected: 16 distinct
   roots (the Raghavan-Roth bound), which is itself a check.
2. **One transposition per fold.**  Each fold's coalescing pair (seeded on its real side) is
   tracked back to s = 1 along the real parameter and matched onto the fibre -- so every fold
   contributes one edge ``(i, j)`` of a graph on the 16 roots.
3. **Group reading.**  A transitive group generated by transpositions is the full symmetric
   group.  So if the seven edges connect all 16 roots, the slice's monodromy is S16, hence
   non-solvable, hence the IK equation of the SR5 has **no solution in radicals** (Harris 1979:
   monodromy = Galois).  If the graph is disconnected, the decomposition is itself the answer
   (and calls for loops around more of the discriminant).

Run::

    python3 -m study.exp38_monodromy_group
"""

from __future__ import annotations

import argparse

import numpy as np

from study import homotopy, sr0
from study import ik_structure as iks
from study.census import census, make_lm_solver
from study.exp11_dh_continuation import link_transforms
from study.exp13_homotopy_sr0_to_sr5 import path_at
from study.exp35_cusp import fold_seeds
from study.exp37_complex_loop import links_at, newton_complex, residual12

BIRTH_FOLDS = [0.655086, 0.656878, 0.657375, 0.658119]
DEATH_FOLDS = [0.718354, 0.799244, 0.961848]


def torus_distance_complex(first: np.ndarray, second: np.ndarray) -> float:
    """Torus distance for complex configurations: equivalence is by *real* 2 pi shifts."""
    delta = np.asarray(first) - np.asarray(second)
    delta = delta - 2.0 * np.pi * np.round(delta.real / (2.0 * np.pi))
    return float(np.linalg.norm(delta))


def make_s_path(s_from: float, s_to: float, avoid: list[float], *, r: float = 5e-4,
                straight_step: float = 2e-3, arc_samples: int = 32) -> list[complex]:
    """The real segment ``s_from -> s_to``, arcing around each avoided fold (upper half-plane).

    A plain real segment passes straight through a fold, where the two coalescing roots collide
    and a real Newton step cannot continue onto the complex pair -- measured: every death-fold
    track stalled with residual ~1e-2.  Arcing around the fold keeps the path regular and the
    continuation smooth; the side (upper half-plane) is a convention, held fixed.
    """
    direction = 1.0 if s_to > s_from else -1.0
    events = sorted(a for a in avoid if min(s_from, s_to) < a < max(s_from, s_to))
    points: list[complex] = []
    cursor = s_from
    for a in events:
        entry = a - direction * r
        count = max(2, int(abs(entry - cursor) / straight_step))
        points.extend(complex(v) for v in np.linspace(cursor, entry, count, endpoint=False))
        # upper half-plane arc from entry to exit: theta sweeps so that Im >= 0 throughout
        start_angle, sweep = (np.pi, -np.pi) if direction > 0 else (0.0, np.pi)
        thetas = start_angle + sweep * np.linspace(0.0, 1.0, arc_samples, endpoint=False)
        points.extend(a + r * np.exp(1j * thetas))
        cursor = a + direction * r
    count = max(2, int(abs(s_to - cursor) / straight_step))
    points.extend(complex(v) for v in np.linspace(cursor, s_to, count, endpoint=False))
    points.append(complex(s_to))
    return points


def track_path(base_links, offset: float, target: np.ndarray, q0: np.ndarray,
               s_points: list[complex], *, max_step: float = 0.1,
               tolerance: float = 1e-10) -> tuple[np.ndarray, float, bool]:
    """Carry one root along a given sequence of (complex) parameter values.

    Adaptive halving as in exp37's loop tracker: big steps and residuals are refused.
    """
    q = np.asarray(q0, dtype=complex)
    worst = 0.0
    s_prev = complex(s_points[0])
    for s_goal in s_points[1:]:
        span, accepted = s_goal - s_prev, False
        for _ in range(8):
            s_mid = s_prev + span
            candidate, residual = newton_complex(links_at(base_links, offset, s_mid), q, target)
            step = float(np.linalg.norm(candidate - q))
            if step <= max_step and residual < tolerance:
                q, worst, accepted = candidate, max(worst, residual), True
                s_prev = s_mid
                break
            span *= 0.5
        if not accepted:
            return q, worst, False
    return q, worst, True


def pair_at_fold(base_links, offset: float, target: np.ndarray, path, q_star: np.ndarray,
                 s_star: float, circular, *, rho: float = 1e-3):
    """The coalescing pair on the fold's real side, seeded along the Jacobian's kernel."""
    kernel = np.linalg.svd(homotopy.jacobian_q(path(s_star), q_star))[2][-1]
    kernel = kernel / np.linalg.norm(kernel)
    for s0 in (s_star + rho, s_star - rho):
        found: list[np.ndarray] = []
        for scale in (0.02, 0.05, 0.1):
            for sign in (1.0, -1.0):
                q, residual = homotopy.correct(path(s0), q_star + sign * scale * kernel,
                                               target, tolerance=1e-12)
                if residual > 1e-9:
                    continue
                if iks.configuration_distance(q, q_star, circular) > 0.25:
                    continue
                if not any(iks.configuration_distance(q, old, circular) < 1e-3
                           for old in found):
                    found.append(q)
        if len(found) == 2:
            return s0, found
    return None, []


def main() -> int:
    """Measure the transposition graph of the SR5 fold spectrum."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--rho", type=float, default=1e-3)
    args = parser.parse_args()

    offset = float(link_transforms()[4][1, 3])
    path = path_at(offset)
    base_links = link_transforms()
    sr5_model = sr0.robot(base_links)
    circular = iks.circular_joints(sr5_model)
    rng = np.random.default_rng(0)
    q_true = rng.uniform(-2.0, 2.0, sr5_model.num_dof)
    target = sr5_model.fk(q_true)

    print("phase A.1: fold spectrum (exp35 machinery)")
    fibre0 = sr0.solve(sr0.robot(), target)
    folds = fold_seeds(path, target, fibre0)
    print(f"  {len(folds)} folds: {[f'{s:.6f}' for s, _ in folds]}")

    print("phase A.2: real fibre at s=1 (census, torus-deduplicated, physically admissible)")
    census1 = census(sr5_model, target, solver=make_lm_solver(sr5_model), seeds=400,
                     rng=np.random.default_rng(2))
    fibre: list[np.ndarray] = []
    for candidate in census1.solutions:
        if not iks.physically_admissible(sr5_model, candidate):
            continue
        if any(iks.torus_distance(candidate, kept) < 1e-3 for kept in fibre):
            continue
        fibre.append(candidate)
    print(f"  real solutions at s=1: {len(fibre)}")

    print("phase A.3: complex roots from the three death folds, tracked to s=1")
    pairs: dict[int, tuple[float, list[np.ndarray]]] = {}
    for fold_index, (s_star, q_star) in enumerate(folds):
        label = "birth" if any(abs(s_star - b) < 1e-4 for b in BIRTH_FOLDS) else "death"
        s0, pair = pair_at_fold(base_links, offset, target, path, q_star, s_star, circular,
                                rho=args.rho)
        if not pair:
            print(f"  fold s*={s_star:.6f} ({label}): pair not found on either side")
            continue
        pairs[fold_index] = (s0, pair)
        print(f"  fold s*={s_star:.6f} ({label}): pair at s0={s0:.4f}, "
              f"distances to q* {iks.configuration_distance(pair[0], q_star, circular):.4f} / "
              f"{iks.configuration_distance(pair[1], q_star, circular):.4f}")

    all_fold_s = [s for s, _ in folds]
    for fold_index, (s0, pair) in pairs.items():
        s_star = folds[fold_index][0]
        if any(abs(s_star - d) < 1e-4 for d in DEATH_FOLDS):
            for side, q0 in enumerate(pair):
                q_end, worst, ok = track_path(base_links, offset, target, q0,
                                              make_s_path(s0, 1.0, all_fold_s))
                residual = float(np.linalg.norm(
                    residual12(links_at(base_links, offset, 1.0), q_end, target)))
                print(f"    death fold {s_star:.6f} pair {side}: -> s=1 ok={ok} "
                      f"worst {worst:.1e} residual {residual:.1e} |imag| "
                      f"{float(np.abs(q_end.imag).max()):.1e}")
                if ok and residual < 1e-8:
                    if not any(torus_distance_complex(q_end, old) < 1e-2 for old in fibre):
                        fibre.append(q_end)
    print(f"  fibre after adding complex roots: {len(fibre)} (expect 16)")

    print("phase B: transposition edges (track each fold's pair back to s=1)")
    edges: list[tuple[int, int, float]] = []
    for fold_index, (s0, pair) in pairs.items():
        s_star = folds[fold_index][0]
        endpoints = []
        for q0 in pair:
            q_end, worst, ok = track_path(base_links, offset, target, q0,
                                          make_s_path(s0, 1.0, all_fold_s))
            if not ok:
                endpoints.append(None)
                continue
            distances = [torus_distance_complex(q_end, member) for member in fibre]
            endpoints.append(int(np.argmin(distances)) if min(distances) < 1e-2 else None)
        if endpoints[0] is not None and endpoints[1] is not None:
            edges.append((endpoints[0], endpoints[1], s_star))
            print(f"  fold s*={s_star:.6f}: transposition ({endpoints[0]}, {endpoints[1]})")
        else:
            print(f"  fold s*={s_star:.6f}: endpoint matching failed {endpoints}")

    print("phase C: the group generated by the fold transpositions")
    parent = list(range(len(fibre)))

    def find(item: int) -> int:
        while parent[item] != item:
            parent[item] = parent[parent[item]]
            item = parent[item]
        return item

    for i, j, _ in edges:
        parent[find(i)] = find(j)
    components: dict[int, list[int]] = {}
    for index in range(len(fibre)):
        components.setdefault(find(index), []).append(index)
    sizes = sorted((len(c) for c in components.values()), reverse=True)
    print(f"  {len(edges)} edges on {len(fibre)} roots -> components of sizes {sizes}")
    if len(fibre) == 16 and sizes == [16]:
        print("  CONNECTED: a transitive group generated by transpositions is S16 --")
        print("  the slice's monodromy is S16, non-solvable, hence NO radical solution")
        print("  (Harris 1979: monodromy = Galois over the function field)")
    else:
        print("  not connected: the measured subgroup decomposes; more of the discriminant")
        print("  must be looped before the solvability question is settled")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
