#!/usr/bin/env python3
"""exp40: the monodromy of the s-family beyond the seven real folds -- complex branch points.

exp38 measured the seven transpositions of the *real* fold spectrum; the transposition graph on
the 16 roots came out disconnected ([3,3,3,2,1,1,1,1,1]), so the solvability question is open.
But the discriminant of the s-family is a curve in the *complex* s-plane: the seven real folds
are only its real points.  Every simple branch point contributes one transposition to the
slice's monodromy group, and a transitive group generated by transpositions is S16 (hence
non-solvable, hence no radical solution).  So the next generators live off the real axis.

Pipeline:

1. **Complex branch-point census.**  Seed ``(q, s)`` complex near the family (track a random
   base-fibre root to a random complex ``s``), then Newton on the augmented system
   ``[err6; det J] = 0`` (7 equations, 7 complex unknowns).  The error is the complex-safe
   pair ``(position, vee(R_t R_c^T - R_c R_t^T)/2)`` -- ``homotopy.se3_error`` is unusable in
   complex (arccos).
2. **Loops.**  For each new branch point (upper half-plane only; conjugates give inverses):
   track all 16 roots of the s=1 fibre out, around a small circle, and back; read the
   permutation on the base fibre directly.
3. **Graph update.**  Add the new transpositions to exp38's seven edges; report components.

Run::

    python3 -m study.exp40_complex_branches
"""

from __future__ import annotations

import argparse

import numpy as np

from study import ik_structure as iks
from study import sr0
from study.census import census, make_lm_solver
from study.exp11_dh_continuation import link_transforms
from study.exp13_homotopy_sr0_to_sr5 import path_at
from study.exp35_cusp import fold_seeds
from study.exp37_complex_loop import fk_complex, links_at
from study.exp38_monodromy_group import (
    make_s_path,
    pair_at_fold,
    torus_distance_complex,
    track_path,
)


def err6_complex(links: list[np.ndarray], q: np.ndarray, target: np.ndarray) -> np.ndarray:
    """Complex-safe 6-component pose error: position + antisymmetric rotation part."""
    current = fk_complex(links, q)
    position = current[:3, 3] - target[:3, 3]
    spin = target[:3, :3] @ current[:3, :3].T - current[:3, :3] @ target[:3, :3].T
    rotation = 0.5 * np.array([spin[2, 1] - spin[1, 2], spin[0, 2] - spin[2, 0],
                               spin[1, 0] - spin[0, 1]])
    return np.concatenate([position, rotation])


def _det_jac(links, q, target) -> complex:
    """det of the 6x6 err6-Jacobian at q."""
    jacobian = np.zeros((6, 6), dtype=complex)
    for index in range(6):
        plus, minus = q.copy(), q.copy()
        plus[index] += 1e-7
        minus[index] -= 1e-7
        jacobian[:, index] = (err6_complex(links, plus, target) - err6_complex(links, minus, target)) / 2e-7
    return np.linalg.det(jacobian)


def refine_branch(base_links, offset: float, target: np.ndarray, q0: np.ndarray, s0: complex,
                  *, iterations: int = 60, tolerance: float = 1e-12):
    """Newton on the augmented system [err6; det J] = 0 in complex (q, s)."""
    y = np.concatenate([np.asarray(q0, dtype=complex), [complex(s0)]])

    def augmented(z: np.ndarray) -> np.ndarray:
        q, s = z[:6], z[6]
        links = links_at(base_links, offset, s)
        return np.concatenate([err6_complex(links, q, target), [_det_jac(links, q, target)]])

    for _ in range(iterations):
        value = augmented(y)
        if float(np.linalg.norm(value)) < tolerance:
            break
        jacobian = np.zeros((7, 7), dtype=complex)
        for column in range(7):
            step = np.zeros(7, dtype=complex)
            step[column] = 1e-7
            jacobian[:, column] = (augmented(y + step) - augmented(y - step)) / 2e-7
        update = np.linalg.lstsq(jacobian, -value, rcond=None)[0]
        if float(np.linalg.norm(update)) > 0.5:
            break
        y = y + update
    return y, float(np.linalg.norm(augmented(y)))


def main() -> int:
    """Census complex branch points, loop them, and update the transposition graph."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--seeds", type=int, default=400, help="complex census seeds")
    parser.add_argument("--max-loops", type=int, default=12)
    args = parser.parse_args()

    offset = float(link_transforms()[4][1, 3])
    path = path_at(offset)
    base_links = link_transforms()
    sr5_model = sr0.robot(base_links)
    circular = iks.circular_joints(sr5_model)
    rng = np.random.default_rng(0)
    q_true = rng.uniform(-2.0, 2.0, sr5_model.num_dof)
    target = sr5_model.fk(q_true)

    print("phase 0: the seven real folds + the full fibre at s=1 (exp38's construction)")
    fibre0 = sr0.solve(sr0.robot(), target)
    folds = fold_seeds(path, target, fibre0)
    real_fold_s = [s for s, _ in folds]
    census1 = census(sr5_model, target, solver=make_lm_solver(sr5_model), seeds=400,
                     rng=np.random.default_rng(2))
    fibre: list[np.ndarray] = []
    for candidate in census1.solutions:
        if not iks.physically_admissible(sr5_model, candidate):
            continue
        if any(iks.torus_distance(candidate, kept) < 1e-3 for kept in fibre):
            continue
        fibre.append(candidate)
    for s_star, q_star in folds:
        if not any(abs(s_star - d) < 1e-4 for d in (0.718354, 0.799244, 0.961848)):
            continue
        s0, pair = pair_at_fold(base_links, offset, target, path, q_star, s_star, circular)
        for q0 in pair:
            q_end, _, ok = track_path(base_links, offset, target, q0,
                                               make_s_path(s0, 1.0, real_fold_s))
            if ok and not any(torus_distance_complex(q_end, old) < 1e-2 for old in fibre):
                fibre.append(q_end)
    print(f"  fibre at s=1: {len(fibre)} roots (expect 16)")
    if len(fibre) != 16:
        print("  fibre incomplete -- stopping")
        return 1

    print(f"phase 1: complex branch-point census ({args.seeds} seeds)")
    branch_points: list[tuple[complex, np.ndarray]] = []
    attempts = converged = 0
    rng_seeds = np.random.default_rng(17)
    for _ in range(args.seeds):
        s_try = 0.4 + 1.0 * rng_seeds.random() + 0.4 * rng_seeds.normal() * 1j
        q_seed = fibre[int(rng_seeds.integers(len(fibre)))]
        tracked, _, ok = track_path(
            base_links, offset, target, q_seed,
            [complex(1.0) + (s_try - 1.0) * t for t in np.linspace(0, 1, 60)[1:]])
        if not ok:
            continue
        attempts += 1
        y, residual = refine_branch(base_links, offset, target, tracked, s_try)
        if residual > 1e-9:
            continue
        converged += 1
        s_c, q_c = y[6], y[:6]
        if any(abs(s_c - known) < 1e-4 for known in real_fold_s):
            continue
        if any(abs(s_c - s_old) < 1e-4 and torus_distance_complex(q_c, q_old) < 0.05
               for s_old, q_old in branch_points):
            # torus-aware dedup: the first version used a plain norm and double-counted
            # the fold at 1.047164, which is one point at two 2pi-shifted representatives
            continue
        branch_points.append((s_c, q_c))
        print(f"  branch point at s = {s_c.real:.6f}{s_c.imag:+.6f}i "
              f"(residual {residual:.1e})")
    print(f"  {len(branch_points)} new branch points (from {converged} converged of "
          f"{attempts} trackable seeds)")

    print("phase 2: loops around the new branch points (upper half-plane only)")
    edges: list[tuple[int, int]] = []
    for s_c, _ in [bp for bp in branch_points if bp[0].imag > 1e-9][: args.max_loops]:
        radius = 0.2 * min(
            [abs(s_c - other) for other, _ in branch_points if other != s_c]
            + [abs(s_c - real) for real in real_fold_s] + [abs(s_c - 1.0)]
        )
        radius = min(max(radius, 1e-4), 0.05)
        out_and_circle = (
            make_s_path_complex(1.0, s_c + radius, real_fold_s)
            + [s_c + radius * np.exp(1j * t) for t in np.linspace(0, 2 * np.pi, 97)[1:]]
            + make_s_path_complex(s_c + radius, 1.0, real_fold_s)[1:]
        )
        images: list[int] = []
        for q0 in fibre:
            q_end, _, ok = track_path(base_links, offset, target, q0, out_and_circle)
            if not ok:
                images.append(-1)
                continue
            distances = [torus_distance_complex(q_end, member) for member in fibre]
            images.append(int(np.argmin(distances)) if min(distances) < 1e-2 else -1)
        moved = [(i, j) for i, j in enumerate(images) if j >= 0 and i != j]
        print(f"  loop around s={s_c.real:.4f}{s_c.imag:+.4f}i (r={radius:.1e}): "
              f"moved {moved}, untracked {images.count(-1)}")
        edges.extend(moved)
    print(f"phase 3: graph update -- {len(edges)} new edge(s)")
    print(f"  new edges: {edges}")
    return 0


def make_s_path_complex(s_from: complex, s_to: complex, avoid_real: list[float],
                        *, samples: int = 120) -> list[complex]:
    """Straight complex segment, nudged around the real fold points if it passes near them."""
    points = [s_from + (s_to - s_from) * t for t in np.linspace(0, 1, samples)]
    cleaned: list[complex] = []
    for point in points:
        for a in avoid_real:
            if abs(point - a) < 3e-3:
                point = point + 3e-3 * 1j
        cleaned.append(complex(point))
    return cleaned


if __name__ == "__main__":
    raise SystemExit(main())
