#!/usr/bin/env python3
"""exp44: the monodromy group from the measured transposition edges -- the solvability verdict.

The edges are kimi's measurements (`collab/day06-result.md` R15 for the seven real folds,
`collab/day08-result.md` R20 for three complex branch points), each obtained by looping around a
discriminant point and reading the permutation of the sixteen roots, with the local-monodromy control
that a fold or branch point contributes a *transposition*.

The group-theoretic content needs no new measurement: a transitive permutation group generated by
transpositions is the full symmetric group on that orbit, and a subgroup of a solvable group is
solvable.  So exhibiting one component of size >= 5 connected by transpositions proves the *whole*
monodromy group is non-solvable, and by Harris (monodromy = Galois group for a generic base point) the
IK equation then has **no solution in radicals**.  This script verifies the two steps computationally --
component structure, and that the transpositions really generate the full symmetric group on each
component (by closure, which is affordable at these sizes).

Run::

    python3 -m study.exp44_group_from_edges
"""

from __future__ import annotations

#: (fold or branch point, transposition) as measured by kimi; the first seven are real folds, the last
#: three complex branch points of the parameter slice.
EDGES: tuple[tuple[str, tuple[int, int]], ...] = (
    ("fold 0.655086 (birth)", (10, 0)),
    ("fold 0.656878 (birth)", (13, 7)),
    ("fold 0.657375 (birth)", (9, 14)),
    ("fold 0.658119 (birth)", (1, 8)),
    ("fold 0.718354 (death)", (10, 11)),
    ("fold 0.799244 (death)", (12, 13)),
    ("fold 0.961848 (death)", (14, 15)),
    ("branch point 1.0701+0.0138i", (5, 8)),
    ("branch point 0.8351+0.8215i", (7, 11)),
    ("branch point 0.9088+0.0629i", (0, 12)),
)

#: Number of roots of the fibre (Raghavan-Roth bound).
ROOTS = 16

#: A symmetric group is solvable exactly up to this degree (A_n is simple non-abelian for n >= 5).
SOLVABLE_DEGREE = 4


def components(edges, size: int = ROOTS) -> list[list[int]]:
    """Connected components of the transposition graph."""
    parent = list(range(size))

    def find(item: int) -> int:
        while parent[item] != item:
            parent[item] = parent[parent[item]]
            item = parent[item]
        return item

    for _name, (first, second) in edges:
        parent[find(first)] = find(second)
    groups: dict[int, list[int]] = {}
    for index in range(size):
        groups.setdefault(find(index), []).append(index)
    return sorted((sorted(group) for group in groups.values()), key=len, reverse=True)


def closure_degree(component: list[int], edges, size: int = ROOTS) -> int:
    """Order of the group generated by the transpositions *restricted to* one component.

    Computed by breadth-first closure over permutations of the component's points; affordable because
    the components here are small (720 elements for the size-six one).
    """
    points = component
    index_of = {point: index for index, point in enumerate(points)}
    generators = []
    for _name, (first, second) in edges:
        if first in index_of and second in index_of:
            images = list(range(len(points)))
            a, b = index_of[first], index_of[second]
            images[a], images[b] = images[b], images[a]
            generators.append(tuple(images))
    identity = tuple(range(len(points)))
    seen = {identity}
    frontier = [identity]
    while frontier:
        current = frontier.pop()
        for generator in generators:
            new = tuple(current[generator[i]] for i in range(len(points)))
            if new not in seen:
                seen.add(new)
                frontier.append(new)
    return len(seen)


def _self_test() -> str:
    """Check the closure routine against two known cases."""
    chain = [("t", (0, 1)), ("t", (1, 2))]
    assert closure_degree([0, 1, 2], chain) == 6, "three points, two transpositions -> S3"
    partial = [("t", (0, 1))]
    assert closure_degree([0, 1, 2], partial) == 2, "one transposition -> S2"
    return "closure self-test passed: S3 by two transpositions, S2 by one"


def main() -> int:
    """Print the components, their group orders and the verdict."""
    print(_self_test())
    groups = components(EDGES)
    print(f"transposition graph: {len(EDGES)} edges on {ROOTS} roots -> "
          f"{len(groups)} components, sizes {[len(g) for g in groups]}")
    order = 1
    non_solvable: list[int] = []
    for group in groups:
        group_order = closure_degree(group, EDGES)
        expected = 1
        for value in range(2, len(group) + 1):
            expected *= value
        print(f"  component {group}: order {group_order} "
              f"({'= S' + str(len(group)) if group_order == expected else 'proper subgroup'}), "
              f"{'solvable' if len(group) <= SOLVABLE_DEGREE else 'NON-SOLVABLE'}")
        order *= group_order
        if len(group) > SOLVABLE_DEGREE:
            non_solvable.append(len(group))
    print(f"\nmeasured monodromy subgroup order: {order}")
    if non_solvable:
        print(f"VERDICT: the subgroup contains S{max(non_solvable)}, which is not solvable; a subgroup "
              f"of a solvable group is solvable, so the whole monodromy group is not solvable, and by "
              f"Harris (monodromy = Galois group) the SR5 IK equation has NO SOLUTION IN RADICALS.")
    else:
        print("VERDICT: every component is solvable, so this slice's subgroup is solvable and the "
              "solvability question stays open -- more of the discriminant has to be looped.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
